routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProdukController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\TransaksiController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route Home
Route::get('/', [HomeController::class, 'index']);
Route::get('/about', [HomeController::class, 'about']);
Route::get('/testimonial', [HomeController::class, 'testimonial']);
Route::get('/blog', [HomeController::class, 'blog']);
Route::get('/contact', [HomeController::class, 'contact']);
Route::get('/products', [HomeController::class, 'products'])->name('admin.home')->middleware('is_admin');
Route::get('/products/{item_id}', [HomeController::class, 'detail']);
Route::get('/products1', [HomeController::class, 'products1']);


//CRUD Profile
Route::resource('profile', ProfileController::class)->only('index', 'update');

//CRUD Product
Route::resource('admin', ProdukController::class);

//CRUD Cart
Route::resource('transaksi', TransaksiController::class);


Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');



Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

resources/views/products/detail.blade.php
@extends('Layouts.master')

@section('content')
     <!-- product section -->
     <section class="product_section layout_padding">
        <div class="container">
           <div class="row">
                <div class="col-sm-6 col-md-4 col-lg-3">
                    <div class="box">
                        <div class="img-box">
                            <img src="{{asset('image/' . $produk->image)}}" alt="">
                        </div>
                        <div class="detail-box">
                            <h5>
                                {{$produk->name}}
                            </h5>
                            <h6>
                                Rp {{$produk->harga}}
                            </h6>
                        </div>                         
                    </div>
                   
                </div>
                <div class="container my-2">
                      <h5 class="card-text">{{$produk->deskripsi}}.</h5>
                </div>
            </div>
            <div class="d-flex justify-center-content my-4">
                <a href="/products" class="btn btn-primary" role="button" style="width: 200px;">Back</a>
            </div>

        </div>
     </section>
     <!-- end product section -->
     <!-- footer section -->
@endsection

resources/views/products/products.blade.php
@extends('Layouts.master')

@section('content')
     <!-- product section -->
     <section class="product_section layout_padding">
        <div class="container">
           <div class="heading_container heading_center">
              <h2>
                 Our <span>products</span>
              </h2>
           </div>           
           <div class="row">
                    @forelse ($produk as $item)
                    {{-- card automasi looping --}}
                        <div class="col-sm-6 col-md-4 col-lg-3">
                            <div class="box">
                                <div class="option_container">
                                    <div class="options">
                                        @auth
                                            <form action="{{ route('transaksi.store') }}" method="POST">
                                            @csrf
                                            <input type="hidden" name="produk_id" value={{$item->id}}>
                                            <button class="btn btn-block btn-secondary" type="submit">
                                            <i class="fa fa-shopping-cart"></i>  Add To Cart
                                            </button>
                                        </form>
                                        <a href="#" class="option2">
                                            Buy Now
                                        </a>
                                        <a href="/products/{{$item->id}}" class="option2">
                                            Detail
                                        </a>      
                                        @endauth
                                        @guest
                                        <a href="/login" class="option1"
                                        data-toggle="modal" data-target="#loginModal">{{ __('Add to Cart') }}
                                        </a>
                                        <a href="/login" class="option2"
                                        data-toggle="modal" data-target="#loginModal">{{ __('Buy Now') }}
                                        </a>
                                        <a href="/login" class="option2"
                                        data-toggle="modal" data-target="#loginModal">{{ __('Detail') }}
                                        </a>       
                                        @endguest
                                        
                                                                                                    
                                    </div>
                                </div>
                                <div class="img-box">
                                    <img src="{{asset('image/' . $item->image)}}" alt="">
                                </div>
                                <div class="detail-box">
                                    <h5>
                                        {{$item->name}}
                                    </h5>
                                    <h6>
                                        Rp {{$item->harga}}
                                    </h6>
                                </div>
                            </div>

                        </div>
                    @empty
                        <h2>Tidak ada data</h2>
            
                    @endforelse
                

           </div>         
        </div>
     </section>
     <!-- end product section -->
     <!-- footer section -->
@endsection